<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Customers\**" />
    <Compile Remove="Drivers\**" />
    <Compile Remove="Notifications\**" />
    <Compile Remove="Shipments\**" />
    <Compile Remove="Vechicles\**" />
    <EmbeddedResource Remove="Customers\**" />
    <EmbeddedResource Remove="Drivers\**" />
    <EmbeddedResource Remove="Notifications\**" />
    <EmbeddedResource Remove="Shipments\**" />
    <EmbeddedResource Remove="Vechicles\**" />
    <None Remove="Customers\**" />
    <None Remove="Drivers\**" />
    <None Remove="Notifications\**" />
    <None Remove="Shipments\**" />
    <None Remove="Vechicles\**" />
  </ItemGroup>

</Project>
