<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Common\" />
    <Folder Include="Customers\" />
    <Folder Include="Drivers\" />
    <Folder Include="SharedKernel\" />
    <Folder Include="Notifications\" />
    <Folder Include="Vechicles\" />
    <Folder Include="Shipments\" />
  </ItemGroup>

</Project>
